# Generated by Django 3.1 on 2020-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesselo', '0002_auto_20200829_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='ties',
            field=models.IntegerField(default=0),
        ),
    ]
