# Generated by Django 3.1 on 2020-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesselo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_white', models.CharField(max_length=64)),
                ('user_black', models.CharField(max_length=64)),
                ('white_win', models.CharField(max_length=64)),
                ('match_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_send', models.CharField(max_length=64)),
                ('user_pending', models.CharField(max_length=64)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='elo',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elo',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
